/**
 * 事件总线事件名常量（`02 §7.6`）。
 *
 * 命名规范：`pet://<域>`。**新增事件必须先登记到 `02 §7.6` 再在此处添加**（C8）。
 */
export const PET_EVENT = {
  /** core → 宠物窗口：`RenderFrameCmd` v2，渲染 tick（2~60Hz）。 */
  FRAME: 'pet://frame',
  /** core → 宠物窗口：`BubbleCmd`，气泡变更时。 */
  BUBBLE: 'pet://bubble',
  /** core → 宠物窗口：`ParticleCmd`，交互粒子触发时（S3-M6 登记）。 */
  FX: 'pet://fx',
  /** core → 宠物窗口：`MenuCmd`，右键单击命中时（S3-M6 登记）。 */
  MENU: 'pet://menu',
  /** core → 设置窗口：`PetSnapshotV2`，1Hz。 */
  STATE: 'pet://state',
  /** core → 设置窗口：需求属性跨档时。 */
  NEEDS: 'pet://needs',
  /** core → 全部：`ActivitySnapshot`，状态迁移时。 */
  ACTIVITY: 'pet://activity',
  /** core → 设置窗口：金币 / 背包变更时。 */
  ECONOMY: 'pet://economy',
  /** core → 全部：情绪等级变更时。 */
  EMOTION: 'pet://emotion',
  /** core → 宠物窗口：`CoaxCmd`，道歉三部曲进度环 / 离家态变更时（S4-M3 登记）。 */
  COAX: 'pet://coax',
  /** core → 全部：配置摘要变更时。 */
  CONFIG: 'pet://config',
  /** core → 设置窗口：性能采样，5s。 */
  PERF: 'pet://perf',
  /** 平台 → app：托盘动作。 */
  TRAY: 'pet://tray',
  /** app → 全部：`SelfCheckReport` 摘要，30s 周期自检时（S1-M4 登记）。 */
  SELFCHECK: 'pet://window/selfcheck',
} as const;

/** 事件名联合类型（`02 §7.6` 全量清单）。 */
export type PetEventName = (typeof PET_EVENT)[keyof typeof PET_EVENT];

// <auto-generated:schema-manifest>
// 本区块由 scripts/gen-types.mjs 自动生成；请勿手改。
// 共 11 份 schema（schemars 生成）。改 Rust 配置结构后请重跑：
//   cargo run -p dp-core --features schema --bin export-schemas && node scripts/gen-types.mjs
export interface SchemaManifestEntry {
  name: string;
  bytes: number;
  sha256: string;
}
export const SCHEMA_MANIFEST: readonly SchemaManifestEntry[] = [
  { name: "achievements", bytes: 2289, sha256: "829d6fc2bc39c01f4c78f959a546d136b04e0020db02a37cef23a3fcc216b41c" },
  { name: "actions", bytes: 6745, sha256: "d67315391f05bfcec048e2630baeb0ae8403ec9d2926d832297822c9e7c840c0" },
  { name: "activities", bytes: 25261, sha256: "41fe1db910686e512071cbed35209fac5db96111e447e4be2cc687f1074cb707" },
  { name: "animation", bytes: 24267, sha256: "84a5d10c3d0ceb177bff9f34092b40cfe8958d8373897f2d7a994b95d1732368" },
  { name: "character", bytes: 13208, sha256: "6d75d3599d97b4c0afe62cc1358285e60302c29d339483441c6201a555190e52" },
  { name: "emotion", bytes: 47237, sha256: "7576f0435d884e843937c3057d1e0fc30c936d06a58d72974dc8debb5198026a" },
  { name: "lines", bytes: 2660, sha256: "c6ab56448db7dc7030807dfb587a68844453f784389cc52b4330417a258c51ef" },
  { name: "needs", bytes: 31862, sha256: "928a7d1153bea03c1bab3891d53c38fdd72ba8547554bf9d5c4545be6bce4f81" },
  { name: "schedule", bytes: 4714, sha256: "b01fb59cbedd8a0ab5aca7cac8c14a19a89cf570f9e320c5767c5b773429b4c5" },
  { name: "settings", bytes: 17920, sha256: "d529c60c1d6ed30c0486b614d000188c3989fa0246efc0a079a0e92efd9a99da" },
  { name: "shop", bytes: 7059, sha256: "c165b57c2548436699382d0663283525dbbb3564ce1615db24a84fb5326b265b" },
];
// </auto-generated:schema-manifest>
