#!/usr/bin/env node
/* global Buffer */
/**
 * gen-types.mjs —— Rust serde 结构 → 配置 schema 漂移守卫（S8-M8 / T-01）。
 *
 * schemars 在编译期生成 `resources/schema/*.schema.json`（11 份）；本脚本把每份
 * schema 的规范化内容指纹（sha256）写进 `src/shared/types.ts` 的自动生成区块，
 * 并在 `--check` 模式下与入库区块比对。若 Rust 侧改了 `#[derive]` 结构而没重跑
 * `export-schemas` / 没同步本区块，CI 即非零退出——这就是「零漂移」闸门。
 *
 * 真正的 TS 接口展开留待后续；本卡先把「生成 → 入库 → 校验」闭环跑通（≥10 份）。
 *
 * 用法：
 *   node scripts/gen-types.mjs           # 生成并写回 types.ts 自动区块
 *   node scripts/gen-types.mjs --check   # 只校验，漂移则 exit 1（CI 用）
 *   node scripts/gen-types.mjs --out <p> # 指定输出文件（默认 src/shared/types.ts）
 *
 * 约束：脚本内禁止出现汉字字面量（C1）；路径一律相对仓库根解析。
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const MARK_START = '// <auto-generated:schema-manifest>';
const MARK_END = '// </auto-generated:schema-manifest>';

function repoRoot() {
  // scripts/gen-types.mjs → 仓库根 = scripts/..
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
}

function sha256(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

/** 规范化 JSON：按键排序，去掉格式空白，使 JSON.stringify 字节稳定。 */
function canonicalize(value) {
  if (value === null || typeof value !== 'object') return value;
  if (Array.isArray(value)) return value.map(canonicalize);
  const out = {};
  for (const key of Object.keys(value).sort()) out[key] = canonicalize(value[key]);
  return out;
}

function collectSchemas(root) {
  const dir = path.join(root, 'resources', 'schema');
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.schema.json'))
    .sort();
  const manifest = [];
  for (const file of files) {
    const raw = fs.readFileSync(path.join(dir, file), 'utf8');
    const parsed = JSON.parse(raw);
    const canonical = JSON.stringify(canonicalize(parsed));
    manifest.push({
      name: file.replace(/\.schema\.json$/, ''),
      bytes: Buffer.byteLength(raw, 'utf8'),
      sha: sha256(canonical),
    });
  }
  return manifest;
}

function renderBlock(manifest) {
  const lines = [
    MARK_START,
    '// 本区块由 scripts/gen-types.mjs 自动生成；请勿手改。',
    `// 共 ${manifest.length} 份 schema（schemars 生成）。改 Rust 配置结构后请重跑：`,
    '//   cargo run -p dp-core --features schema --bin export-schemas && node scripts/gen-types.mjs',
    'export interface SchemaManifestEntry {',
    '  name: string;',
    '  bytes: number;',
    '  sha256: string;',
    '}',
    'export const SCHEMA_MANIFEST: readonly SchemaManifestEntry[] = [',
  ];
  for (const e of manifest) {
    lines.push(`  { name: ${JSON.stringify(e.name)}, bytes: ${e.bytes}, sha256: ${JSON.stringify(e.sha)} },`);
  }
  lines.push('];');
  lines.push(MARK_END);
  return lines.join('\n');
}

function replaceBlock(existing, block) {
  const re = new RegExp(`${MARK_START}[\\s\\S]*?${MARK_END}`, 'm');
  if (re.test(existing)) return existing.replace(re, block);
  return existing.replace(/\s*$/, '') + '\n\n' + block + '\n';
}

function extractBlock(text) {
  const re = new RegExp(`${MARK_START}[\\s\\S]*?${MARK_END}`, 'm');
  const m = text.match(re);
  return m ? m[0] : null;
}

function main() {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  let out = path.join('src', 'shared', 'types.ts');
  const outIdx = args.indexOf('--out');
  if (outIdx >= 0 && args[outIdx + 1]) out = args[outIdx + 1];

  const root = repoRoot();
  const manifest = collectSchemas(root);
  if (manifest.length < 10) {
    console.error(`[gen-types] expected >=10 schemas, found ${manifest.length}`);
    process.exit(2);
  }
  const block = renderBlock(manifest);
  const outPath = path.isAbsolute(out) ? out : path.join(root, out);
  const existing = fs.readFileSync(outPath, 'utf8');

  if (check) {
    const current = extractBlock(existing);
    if (current === null) {
      console.error('[gen-types] auto block missing; run `node scripts/gen-types.mjs`');
      process.exit(1);
    }
    if (current !== block) {
      console.error('[gen-types] drift detected: schema manifest out of date');
      console.error('[gen-types] run `cargo run -p dp-core --features schema --bin export-schemas && node scripts/gen-types.mjs`');
      process.exit(1);
    }
    console.log(`[gen-types] OK: ${manifest.length} schemas in sync`);
    process.exit(0);
  }

  fs.writeFileSync(outPath, replaceBlock(existing, block), 'utf8');
  console.log(`[gen-types] wrote manifest: ${manifest.length} schemas -> ${out}`);
}

main();
